# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180716_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
